

steps:
  - name: "python"
    entrypoint: bash
    args:
      - "-c"
      - |
        cd api  # Change to the 'api' directory
        pip install -r requirements.txt  # Install dependencies
      - "pip"
      - "install"
      - "-r"
      - "requirements.txt"

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--project=concise-rex-400619", ]
